### ISSUE TITLE
[Idea] Use structure or simple data object

### ISSUE THREAD

**Issue by kookma** [sanjayg0/epcms#2]
I am reading some the code and note that block like below

```
% Material parameters for 316SS
Eyoung    = 200e9;  % Pa
Sy        = 250e6;  % Pa
K         = 1182e6; % Pa
eps_dot_0 = 1e-3;   % 1/seconds
n         = .47;    % strain hardening exponent
m         = 0.02;   % strain rate sensitivity parameter
```

Why not to use a a Matlab structure of a simple data object ( a class) to encapsulate and simplify this?

**Comment by sanjayg0** [comment]
Missed your comment, since I have not looked at the repo in awhile.  Sorry about that.
The question about whether or not to use structures is interesting.  From a coding perspective, it makes good sense.  But I wonder if it will make the code harder for students to read, especially since many are not very well trained in coding.
